In [8]:
import pandas as pd
import numpy as np

In [19]:
df = pd.read_csv('narahoteisbases/clientes.csv', sep=';')
df

,id_cliente,nome,cidade_origem,estado_origem,faixa_etaria,tipo_cliente
0,1,Otavio Reis,São Paulo,SP,18-25,PJ
1,2,Larissa Sousa,Curitiba,SC,18-25,pessoa fisica
2,3,Tatiana Coelho,Rio de Janeiro,CE,65+,Corporativo
3,4,Wilson Duarte,Brasília,AM,26-35,corporativo
4,5,Gabriela Lima,Rio de Janeiro,SP,46-55,Pessoa Física
...,...,...,...,...,...,...
296,297,Roberta Leite,Curitiba,DF,56-65,pessoa fisica
297,298,Eduardo Lopes,São Paulo,ES,36-45,PJ
298,299,Vanessa Cavalcanti,Curitiba,AM,46-55,Pessoa Física
299,300,Julia Monteiro,Brasília,PR,36-45,Corporativo
300,47,Carlos Neto,Niterói,RJ,36-45,Corporativo

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id_cliente     301 non-null    int64
 1   nome           301 non-null    str
 2   cidade_origem  301 non-null    str
 3   estado_origem  301 non-null    str
 4   faixa_etaria   272 non-null    str
 5   tipo_cliente   301 non-null    str
dtypes: int64(1), str(5)
memory usage: 14.2 KB

In [11]:
df.isnull().sum().reset_index()

           index   0
0     id_cliente   0
1           nome   0
2  cidade_origem   0
3  estado_origem   0
4   faixa_etaria  29
5   tipo_cliente   0

In [20]:
df[df.duplicated(subset=['nome', 'cidade_origem', 'estado_origem', 'faixa_etaria'], keep=False)].sort_values(by='nome')

,id_cliente,nome,cidade_origem,estado_origem,faixa_etaria,tipo_cliente
43,44,Rafael Cardoso,Fortaleza,RJ,18-25,Corporativo
93,94,Rafael Cardoso,Fortaleza,RJ,18-25,PJ

In [22]:
df[df.isnull() 
.any(axis=1)]

,id_cliente,nome,cidade_origem,estado_origem,faixa_etaria,tipo_cliente
8,9,Wesley Araujo,Belo Horizonte,ES,NaN,Corporativo
14,15,Henrique Rocha,Recife,MG,NaN,Pessoa Física
15,16,Marcos Andrade,São Paulo,RS,NaN,Corporativo
19,20,Thiago Matos,Fortaleza,ES,NaN,Pessoa Física
28,29,Isabela Martins,São Paulo,SC,NaN,Corporativo
38,39,Ivan Azevedo,Curitiba,ES,NaN,Corporativo
42,43,Roberta Leite,Recife,CE,NaN,Corporativo
52,53,Bruno Costa,Recife,SP,NaN,Pessoa Física
68,69,Isabela Martins,Recife,MG,NaN,Corporativo
92,93,Gabriela Lima,Belo Horizonte,PA,NaN,corporativo
95,96,Quezia Nunes,Rio de Janeiro,PA,NaN,Pessoa Física
99,100,Otavio Reis,Rio de Janeiro,ES,NaN,pessoa fisica
107,108,Rafael Cardoso,Brasília,MG,NaN,Corporativo
112,113,Henrique Rocha,Recife,RJ,NaN,Pessoa Física
121,122,Ana Silva,Salvador,PE,NaN,Corporativo
123,124,Ursula Pinto,Salvador,CE,NaN,PJ
142,143,Henrique Rocha,Belo Horizonte,MG,NaN,Pessoa Física
165,166,Kleber Pires,Curitiba,CE,NaN,Pessoa Física
172,173,Elena Santos,Brasília,SC,NaN,Pessoa Física
174,175,Ursula Pinto,São Paulo,MG,NaN,Corporativo
181,182,Thiago Matos,São Paulo,RS,NaN,Pessoa Física
188,189,Thiago Matos,Recife,CE,NaN,Corporativo
199,200,Gustavo Vieira,São Paulo,PR,NaN,Corporativo
201,202,Wilson Duarte,Curitiba,PE,NaN,Corporativo
204,205,Otavio Reis,Brasília,GO,NaN,pf
209,210,Ximena Godoi,Fortaleza,CE,NaN,Corporativo
228,229,Ximena Godoi,Fortaleza,SC,NaN,Pessoa Física
269,270,Lucas Souza,São Paulo,DF,NaN,Corporativo
295,296,Carlos Neto,Recife,PA,NaN,Pessoa Física

In [ ]:
df['cidade_origem'] = df['cidade_origem'].str.strip().str.title()
df['estado_origem'] = df['cidade_origem']