In [104]:
import pandas as pd
import numpy as np

In [105]:
df = pd.read_csv('narahoteisbases/reservas.csv', sep=';')

In [106]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2457 entries, 0 to 2456
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_reserva         2457 non-null   int64
 1   id_unidade         2457 non-null   int64
 2   id_tipo_quarto     2457 non-null   int64
 3   id_cliente         2457 non-null   int64
 4   id_canal           2345 non-null   float64
 5   data_checkin       2457 non-null   str
 6   data_checkout      2457 non-null   str
 7   qtd_diarias        2457 non-null   int64
 8   num_hospedes       2457 non-null   int64
 9   avaliacao_hospede  2120 non-null   float64
 10  status_reserva     2457 non-null   str
 11  forma_pagamento    2457 non-null   str
dtypes: float64(2), int64(6), str(4)
memory usage: 230.5 KB

### Tratamento id_canal

In [107]:
df['id_canal'] = df['id_canal'].astype('Int64')

### Tratamento datas:

In [108]:
df['data_checkin'] = pd.to_datetime(
    df['data_checkin'],
    yearfirst=True
)
df['data_checkout'] = pd.to_datetime(
    df['data_checkout'],
    yearfirst=True
)

### Tratamento de textos:

#### Status reserva:

In [109]:
df['status_reserva'] = df['status_reserva'].str.strip().str.title()

In [110]:
map_status_reserva = {
    'Concluída': 'Confirmada',
    'Concluida': 'Confirmada',
    'Conf.': 'Confirmada',
    'Cancel.': 'Cancelada',
}
df['status_reserva'] = df['status_reserva'].map(map_status_reserva).fillna(df['status_reserva'])

In [111]:
df['status_reserva'].value_counts().reset_index()

  status_reserva  count
0     Confirmada   1968
1      Cancelada    363
2        No-Show    126

#### Forma pagamento:

In [112]:
df['forma_pagamento'].value_counts().reset_index()

      forma_pagamento  count
0            Dinheiro    501
1    Cartão de Débito    499
2                 PIX    484
3       Transferência    467
4   Cartão de Crédito    453
5                  CC      9
6                 Pix      7
7                cred      5
8                 pix      5
9            dinheiro      4
10         C. Crédito      4
11               cash      4
12     cartao credito      3
13                 CD      3
14      transferencia      2
15           DINHEIRO      2
16                ted      2
17                déb      1
18      cartao debito      1
19                TED      1

In [113]:
df['forma_pagamento'] = df['forma_pagamento'].str.strip().str.title()

In [114]:
map_pagamento = {
    'Cash': 'Dinheiro',
    # Debito
    'Cd': 'Cartão De Débito',
    'Déb': 'Cartão De Débito',
    'Cartao Debito': 'Cartão De Débito',
    # Transferencia
    'Ted': 'Transferência',
    'Transferencia': 'Transferência',
    # Credito
    'Cc': 'Cartão De Crédito',
    'Cred': 'Cartão De Crédito',
    'C. Crédito': 'Cartão De Crédito',
    'Cartao Credito': 'Cartão De Crédito',
    'Cartao Credito': 'Cartão De Crédito',
}
df['forma_pagamento'] = df['forma_pagamento'].map(map_pagamento).fillna(df['forma_pagamento'])

In [121]:
df['forma_pagamento'].value_counts().reset_index()

     forma_pagamento  count
0           Dinheiro    504
1   Cartão De Débito    504
2                Pix    494
3  Cartão De Crédito    471
4      Transferência    469

### Duplicatas:

In [115]:
df[df.duplicated(subset=['id_unidade', 'id_tipo_quarto', 'id_cliente', 'id_canal', 'data_checkin', 'data_checkout', 'qtd_diarias', 'num_hospedes', 'avaliacao_hospede', 'status_reserva', 'forma_pagamento'], keep=False)].sort_values(by='id_cliente')

,id_reserva,id_unidade,id_tipo_quarto,id_cliente,id_canal,data_checkin,data_checkout,qtd_diarias,num_hospedes,avaliacao_hospede,status_reserva,forma_pagamento
585,586,5,2,2,2,2024-06-15,2024-06-17,2,1,3.0,Confirmada,Cartão De Crédito
2218,2219,5,2,2,2,2024-06-15,2024-06-17,2,1,3.0,Confirmada,Cartão De Crédito
1342,1343,9,1,13,1,2024-01-26,2024-02-01,6,1,9.0,Confirmada,Dinheiro
273,274,9,1,13,1,2024-01-26,2024-02-01,6,1,9.0,Confirmada,Dinheiro
1334,1335,9,5,38,1,2024-09-16,2024-09-18,2,3,7.0,Confirmada,Cartão De Crédito
1668,1669,9,5,38,1,2024-09-16,2024-09-18,2,3,7.0,Confirmada,Cartão De Crédito
838,839,3,3,52,2,2023-02-23,2023-02-25,2,2,1.0,Confirmada,Transferência
418,419,3,3,52,2,2023-02-23,2023-02-25,2,2,1.0,Confirmada,Transferência
1427,1428,3,1,58,4,2023-07-15,2023-07-17,2,1,3.0,Confirmada,Transferência
846,847,3,1,58,4,2023-07-15,2023-07-17,2,1,3.0,Confirmada,Transferência
715,716,4,5,62,1,2023-04-24,2023-04-25,1,3,9.0,Confirmada,Dinheiro
120,121,4,5,62,1,2023-04-24,2023-04-25,1,3,9.0,Confirmada,Dinheiro
1191,1192,5,1,88,1,2024-03-11,2024-03-14,3,1,4.0,No-Show,Dinheiro
1735,1736,5,1,88,1,2024-03-11,2024-03-14,3,1,4.0,No-Show,Dinheiro
1645,1646,11,4,95,1,2023-12-23,2023-12-26,3,2,NaN,Confirmada,Dinheiro
1946,1947,11,4,95,1,2023-12-23,2023-12-26,3,2,NaN,Confirmada,Dinheiro
596,597,5,1,147,2,2023-08-11,2023-08-14,3,1,2.0,Cancelada,Dinheiro
1828,1829,5,1,147,2,2023-08-11,2023-08-14,3,1,2.0,Cancelada,Dinheiro
877,878,10,4,168,4,2024-12-10,2024-12-12,2,2,6.0,Cancelada,Dinheiro
433,434,10,4,168,4,2024-12-10,2024-12-12,2,2,6.0,Cancelada,Dinheiro
1952,1953,6,2,208,2,2023-12-09,2023-12-11,2,1,9.0,Confirmada,Transferência
1903,1904,6,2,208,2,2023-12-09,2023-12-11,2,1,9.0,Confirmada,Transferência
1355,1356,6,4,223,<NA>,2023-04-08,2023-04-10,2,4,7.0,Confirmada,Pix
1727,1728,6,4,223,<NA>,2023-04-08,2023-04-10,2,4,7.0,Confirmada,Pix
61,62,11,2,227,4,2024-06-21,2024-06-25,4,1,9.0,Confirmada,Cartão De Crédito
104,105,11,2,227,4,2024-06-21,2024-06-25,4,1,9.0,Confirmada,Cartão De Crédito
1505,1506,4,4,239,4,2023-01-09,2023-01-11,2,2,6.0,Confirmada,Pix
1115,1116,4,4,239,4,2023-01-09,2023-01-11,2,2,6.0,Confirmada,Pix
994,995,7,3,290,4,2023-12-16,2023-12-17,1,3,9.0,Confirmada,Dinheiro
1954,1955,7,3,290,4,2023-12-16,2023-12-17,1,3,9.0,Confirmada,Dinheiro

In [116]:
df = df.drop_duplicates(subset=['id_unidade', 'id_tipo_quarto', 'id_cliente', 'id_canal', 'data_checkin', 'data_checkout', 'qtd_diarias', 'num_hospedes', 'avaliacao_hospede', 'status_reserva', 'forma_pagamento'], keep='first')

In [117]:
df[df.duplicated(subset=['id_unidade', 'id_tipo_quarto', 'id_cliente', 'id_canal', 'data_checkin', 'data_checkout', 'qtd_diarias', 'num_hospedes', 'avaliacao_hospede', 'status_reserva', 'forma_pagamento'], keep=False)].sort_values(by='id_cliente')

Empty DataFrame
Columns: [id_reserva, id_unidade, id_tipo_quarto, id_cliente, id_canal, data_checkin, data_checkout, qtd_diarias, num_hospedes, avaliacao_hospede, status_reserva, forma_pagamento]
Index: []

### Nulos e analise final:

In [118]:
df.isnull().sum().reset_index()

                index    0
0          id_reserva    0
1          id_unidade    0
2      id_tipo_quarto    0
3          id_cliente    0
4            id_canal  111
5        data_checkin    0
6       data_checkout    0
7         qtd_diarias    0
8        num_hospedes    0
9   avaliacao_hospede  336
10     status_reserva    0
11    forma_pagamento    0

In [119]:
df[df.isnull() 
.any(axis=1)]

,id_reserva,id_unidade,id_tipo_quarto,id_cliente,id_canal,data_checkin,data_checkout,qtd_diarias,num_hospedes,avaliacao_hospede,status_reserva,forma_pagamento
7,8,4,4,33,3,2023-08-26,2023-09-02,7,2,NaN,No-Show,Dinheiro
10,11,8,3,189,<NA>,2024-10-08,2024-10-13,5,1,8.0,Confirmada,Transferência
12,13,3,3,184,<NA>,2024-02-01,2024-02-02,1,1,2.0,Confirmada,Pix
13,14,4,3,68,3,2024-03-07,2024-03-11,4,3,NaN,Cancelada,Dinheiro
14,15,6,2,173,1,2024-07-20,2024-07-23,3,1,NaN,Cancelada,Transferência
...,...,...,...,...,...,...,...,...,...,...,...,...
2423,2424,8,1,258,3,2023-09-10,2023-09-17,7,1,NaN,Confirmada,Transferência
2425,2426,4,2,6,2,2023-04-17,2023-04-18,1,2,NaN,Confirmada,Transferência
2430,2431,7,1,227,3,2023-05-20,2023-05-27,7,1,NaN,Cancelada,Cartão De Débito
2436,2437,8,3,113,2,2023-07-28,2023-07-31,3,2,NaN,Cancelada,Dinheiro
2444,2445,10,2,266,2,2023-09-06,2023-09-13,7,1,NaN,No-Show,Cartão De Débito

In [120]:
df.info()

<class 'pandas.DataFrame'>
Index: 2442 entries, 0 to 2456
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_reserva         2442 non-null   int64
 1   id_unidade         2442 non-null   int64
 2   id_tipo_quarto     2442 non-null   int64
 3   id_cliente         2442 non-null   int64
 4   id_canal           2331 non-null   Int64
 5   data_checkin       2442 non-null   datetime64[us]
 6   data_checkout      2442 non-null   datetime64[us]
 7   qtd_diarias        2442 non-null   int64
 8   num_hospedes       2442 non-null   int64
 9   avaliacao_hospede  2106 non-null   float64
 10  status_reserva     2442 non-null   str
 11  forma_pagamento    2442 non-null   str
dtypes: Int64(1), datetime64[us](2), float64(1), int64(6), str(2)
memory usage: 250.4 KB