In [1]:
import pandas as pd
import numpy as np

In [2]:
df_antigo = pd.read_csv('narahoteisbases/tipos_quarto.csv', sep=';')
df_novo = pd.read_csv('narahoteisbases_nova/tipos_quarto_novos.csv', sep=';')

In [3]:
df = pd.concat(
    [df_antigo, df_novo],
    ignore_index=True
)
df

   id_tipo_quarto                descricao  capacidade_max valor_diaria_base
0               1                 STANDARD               2         R$ 280,00
1               2                superior                2         R$ 420,00
2               3                   Deluxe               3         R$ 580,00
3               4                    Suite               4         R$ 950,00
4               5             Suíte Master               4       R$ 1.500,00
5               3                   Deluxe               3         R$ 580,00
6               6          Suíte Vista Mar               2         R$ 620,00
7               7  Suíte Master Copacabana               3         R$ 780,00
8               8   Cobertura Presidencial               4         R$ 950,00

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_tipo_quarto     9 non-null      int64
 1   descricao          9 non-null      str
 2   capacidade_max     9 non-null      int64
 3   valor_diaria_base  9 non-null      str
dtypes: int64(2), str(2)
memory usage: 420.0 bytes

In [5]:
df['valor_diaria_base'] = df['valor_diaria_base'].str.replace('.', '', regex=False).str.replace('R$', '', regex=False).str.replace(' ', '', regex=False).str.replace(',', '.', regex=False).astype(float)

In [6]:
df['descricao'] = df['descricao'].str.strip().str.title()

In [7]:
df = df.drop_duplicates(keep='first')

In [8]:
df

   id_tipo_quarto                descricao  capacidade_max  valor_diaria_base
0               1                 Standard               2              280.0
1               2                 Superior               2              420.0
2               3                   Deluxe               3              580.0
3               4                    Suite               4              950.0
4               5             Suíte Master               4             1500.0
6               6          Suíte Vista Mar               2              620.0
7               7  Suíte Master Copacabana               3              780.0
8               8   Cobertura Presidencial               4              950.0